const sliderProduct = [
  {
    id: 1,
    title: "Новый зверь для всех типов кабелей",
    sizeDiscription: "от 1,5 до 130мм",
    diametrDiscription: "90*68*120 см",
    powerDiscription: "3 кВт 380 В",
    price: "209 000 ₽",
    img: "./img/sg-006.png",
  },
  {
    id: 2,
    title: "Самый лучший прибор для наризания кабелей",
    sizeDiscription: "от 2 до 130мм",
    diametrDiscription: "86*68*120 см",
    powerDiscription: "5 кВт 380 В",
    price: "300 000 ₽",
    img: "./img/sg-006.png",
  },
  {
    id: 3,
    title: "Иновационный станок для всех типов кабелей",
    sizeDiscription: "от 4 до 140мм",
    diametrDiscription: "55*68*125 см",
    powerDiscription: "2 кВт 555 В",
    price: "359 000 ₽",
    img: "./img/sg-006.png",
  },
];

const ourProductOld = [
  {
    id: 1,
    type: "guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: "54 990 ₽",
  },
  {
    id: 20,
    type: "sale-guard-press",
    name: "SG-007-1 Станок для разделки кабеля (Автоматический)",
    img: "./img/sg-007.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 33,
    type: "regular",
    name: "SG-008-1 Станок для разделки кабеля",
    img: "./img/sg-008.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 15,
    type: "guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: "54 990 ₽",
  },
  {
    id: 25,
    type: "regular",
    name: "SG-008-1 Станок для разделки кабеля",
    img: "./img/sg-008.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 55,
    type: "sale-guard-press",
    name: "SG-007-1 Станок для разделки кабеля (Автоматический)",
    img: "./img/sg-007.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 12,
    type: "regular",
    name: "SG-008-1 Станок для разделки кабеля",
    img: "./img/sg-008.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 13,
    type: "sale-guard-press",
    name: "SG-007-1 Станок для разделки кабеля (Автоматический)",
    img: "./img/sg-007.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "84 990 ₽",
    priceBefore: "74 990 ₽",
  },
  {
    id: 14,
    type: "guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: "54 990 ₽",
  },
  {
    id: 11,
    type: "guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: "54 990 ₽",
  },
  {
    id: 47,
    type: "sale-guard-press",
    name: "SG-007-1 Станок для разделки кабеля (Автоматический)",
    img: "./img/sg-007.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 5,
    type: "regular",
    name: "SG-008-1 Станок для разделки кабеля",
    img: "./img/sg-008.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 3,
    type: "guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: "54 990 ₽",
  },
  {
    id: 87,
    type: "regular",
    name: "SG-008-1 Станок для разделки кабеля",
    img: "./img/sg-008.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
  {
    id: 90,
    type: "sale-guard-press",
    name: "SG-007-1 Станок для разделки кабеля (Автоматический)",
    img: "./img/sg-007.png",
    weightDiscription: "13кг",
    engineDiscription: "180Вт",
    diametrDiscription: "от 1.5 до 25мм",
    price: "34 990 ₽",
    priceBefore: "24 990 ₽",
  },
];

const ourProduct = [
  {
    id: 1,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7123,
    currency: "₽",
    discount: 2136.9,
  },
  {
    id: 2,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4708,
    currency: "₽",
    discount: 1412.4,
  },
  {
    id: 3,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6613,
    currency: "₽",
    discount: 1983.9,
  },
  {
    id: 4,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5365,
    currency: "₽",
    discount: 1609.5,
  },
  {
    id: 5,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7646,
    currency: "₽",
    discount: 2293.8,
  },
  {
    id: 6,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7333,
    currency: "₽",
    discount: 2199.9,
  },
  {
    id: 7,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8652,
    currency: "₽",
    discount: 2595.6,
  },
  {
    id: 8,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 897,
    currency: "₽",
    discount: 269.1,
  },
  {
    id: 9,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1837,
    currency: "₽",
    discount: 551.1,
  },
  {
    id: 10,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3309,
    currency: "₽",
    discount: 992.7,
  },
  {
    id: 11,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3022,
    currency: "₽",
    discount: 906.6,
  },
  {
    id: 12,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1391,
    currency: "₽",
    discount: 417.3,
  },
  {
    id: 13,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3971,
    currency: "₽",
    discount: 1191.3,
  },
  {
    id: 14,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9301,
    currency: "₽",
    discount: 2790.3,
  },
  {
    id: 15,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 863,
    currency: "₽",
    discount: 258.9,
  },
  {
    id: 16,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9651,
    currency: "₽",
    discount: 2895.3,
  },
  {
    id: 17,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 160,
    currency: "₽",
    discount: 48.0,
  },
  {
    id: 18,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6426,
    currency: "₽",
    discount: 1927.8,
  },
  {
    id: 19,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1702,
    currency: "₽",
    discount: 510.6,
  },
  {
    id: 20,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3780,
    currency: "₽",
    discount: 1134.0,
  },
  {
    id: 21,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 449,
    currency: "₽",
    discount: 134.7,
  },
  {
    id: 22,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 283,
    currency: "₽",
    discount: 84.9,
  },
  {
    id: 23,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8526,
    currency: "₽",
    discount: 2557.8,
  },
  {
    id: 24,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2673,
    currency: "₽",
    discount: 801.9,
  },
  {
    id: 25,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 697,
    currency: "₽",
    discount: 209.1,
  },
  {
    id: 26,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4707,
    currency: "₽",
    discount: 1412.1,
  },
  {
    id: 27,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9573,
    currency: "₽",
    discount: 2871.9,
  },
  {
    id: 28,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9647,
    currency: "₽",
    discount: 2894.1,
  },
  {
    id: 29,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9810,
    currency: "₽",
    discount: 2943.0,
  },
  {
    id: 30,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1982,
    currency: "₽",
    discount: 594.6,
  },
  {
    id: 31,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1601,
    currency: "₽",
    discount: 480.3,
  },
  {
    id: 32,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2146,
    currency: "₽",
    discount: 643.8,
  },
  {
    id: 33,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7812,
    currency: "₽",
    discount: 2343.6,
  },
  {
    id: 34,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8238,
    currency: "₽",
    discount: 2471.4,
  },
  {
    id: 35,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 80,
    currency: "₽",
    discount: 24.0,
  },
  {
    id: 36,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9313,
    currency: "₽",
    discount: 2793.9,
  },
  {
    id: 37,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5133,
    currency: "₽",
    discount: 1539.9,
  },
  {
    id: 38,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9699,
    currency: "₽",
    discount: 2909.7,
  },
  {
    id: 39,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7722,
    currency: "₽",
    discount: 2316.6,
  },
  {
    id: 40,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9435,
    currency: "₽",
    discount: 2830.5,
  },
  {
    id: 41,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2477,
    currency: "₽",
    discount: 743.1,
  },
  {
    id: 42,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4593,
    currency: "₽",
    discount: 1377.9,
  },
  {
    id: 43,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6301,
    currency: "₽",
    discount: 1890.3,
  },
  {
    id: 44,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2224,
    currency: "₽",
    discount: 667.2,
  },
  {
    id: 45,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3747,
    currency: "₽",
    discount: 1124.1,
  },
  {
    id: 46,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 799,
    currency: "₽",
    discount: 239.7,
  },
  {
    id: 47,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5179,
    currency: "₽",
    discount: 1553.7,
  },
  {
    id: 48,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9214,
    currency: "₽",
    discount: 2764.2,
  },
  {
    id: 49,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1838,
    currency: "₽",
    discount: 551.4,
  },
  {
    id: 50,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8609,
    currency: "₽",
    discount: 2582.7,
  },
  {
    id: 51,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4357,
    currency: "₽",
    discount: 1307.1,
  },
  {
    id: 52,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1714,
    currency: "₽",
    discount: 514.2,
  },
  {
    id: 53,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9208,
    currency: "₽",
    discount: 2762.4,
  },
  {
    id: 54,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7086,
    currency: "₽",
    discount: 2125.8,
  },
  {
    id: 55,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7222,
    currency: "₽",
    discount: 2166.6,
  },
  {
    id: 56,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9653,
    currency: "₽",
    discount: 2895.9,
  },
  {
    id: 57,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6610,
    currency: "₽",
    discount: 1983.0,
  },
  {
    id: 58,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4708,
    currency: "₽",
    discount: 1412.4,
  },
  {
    id: 59,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6608,
    currency: "₽",
    discount: 1982.4,
  },
  {
    id: 60,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4425,
    currency: "₽",
    discount: 1327.5,
  },
  {
    id: 61,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1818,
    currency: "₽",
    discount: 545.4,
  },
  {
    id: 62,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2241,
    currency: "₽",
    discount: 672.3,
  },
  {
    id: 63,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3260,
    currency: "₽",
    discount: 978.0,
  },
  {
    id: 64,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8368,
    currency: "₽",
    discount: 2510.4,
  },
  {
    id: 65,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4933,
    currency: "₽",
    discount: 1479.9,
  },
  {
    id: 66,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2303,
    currency: "₽",
    discount: 690.9,
  },
  {
    id: 67,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7580,
    currency: "₽",
    discount: 2274.0,
  },
  {
    id: 68,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7386,
    currency: "₽",
    discount: 2215.8,
  },
  {
    id: 69,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2068,
    currency: "₽",
    discount: 620.4,
  },
  {
    id: 70,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2500,
    currency: "₽",
    discount: 750.0,
  },
  {
    id: 71,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5627,
    currency: "₽",
    discount: 1688.1,
  },
  {
    id: 72,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5737,
    currency: "₽",
    discount: 1721.1,
  },
  {
    id: 73,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5045,
    currency: "₽",
    discount: 1513.5,
  },
  {
    id: 74,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9769,
    currency: "₽",
    discount: 2930.7,
  },
  {
    id: 75,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4635,
    currency: "₽",
    discount: 1390.5,
  },
  {
    id: 76,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2148,
    currency: "₽",
    discount: 644.4,
  },
  {
    id: 77,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2633,
    currency: "₽",
    discount: 789.9,
  },
  {
    id: 78,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6452,
    currency: "₽",
    discount: 1935.6,
  },
  {
    id: 79,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4995,
    currency: "₽",
    discount: 1498.5,
  },
  {
    id: 80,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9160,
    currency: "₽",
    discount: 2748.0,
  },
  {
    id: 81,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2915,
    currency: "₽",
    discount: 874.5,
  },
  {
    id: 82,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8773,
    currency: "₽",
    discount: 2631.9,
  },
  {
    id: 83,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3578,
    currency: "₽",
    discount: 1073.4,
  },
  {
    id: 84,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4987,
    currency: "₽",
    discount: 1496.1,
  },
  {
    id: 85,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 857,
    currency: "₽",
    discount: 257.1,
  },
  {
    id: 86,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 8237,
    currency: "₽",
    discount: 2471.1,
  },
  {
    id: 87,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2924,
    currency: "₽",
    discount: 877.2,
  },
  {
    id: 88,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1982,
    currency: "₽",
    discount: 594.6,
  },
  {
    id: 89,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6108,
    currency: "₽",
    discount: 1832.4,
  },
  {
    id: 90,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 1270,
    currency: "₽",
    discount: 381.0,
  },
  {
    id: 91,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5911,
    currency: "₽",
    discount: 1773.3,
  },
  {
    id: 92,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4321,
    currency: "₽",
    discount: 1296.3,
  },
  {
    id: 93,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 4057,
    currency: "₽",
    discount: 1217.1,
  },
  {
    id: 94,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 2620,
    currency: "₽",
    discount: 786.0,
  },
  {
    id: 95,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6512,
    currency: "₽",
    discount: 1953.6,
  },
  {
    id: 96,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 5285,
    currency: "₽",
    discount: 1585.5,
  },
  {
    id: 97,
    type: " sale-guard-press",
    name: "S2-3 Автоматический мини",
    img: "./img/S2-3.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 3171,
    currency: "₽",
    discount: 951.3,
  },
  {
    id: 98,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 6717,
    currency: "₽",
    discount: 2015.1,
  },
  {
    id: 99,
    type: "regular",
    name: "sg-008 Автоматический мини",
    img: "./img/sg-008.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 9822,
    currency: "₽",
    discount: 2946.6,
  },
  {
    id: 100,
    type: "guard-press",
    name: "sg-007 Автоматический мини",
    img: "./img/sg-007.png",
    weightDiscription: "16кг",
    engineDiscription: "190Вт",
    diametrDiscription: "от 3 до 35мм",
    price: 7930,
    currency: "₽",
    discount: 2379.0,
  },
];
export { sliderProduct, ourProduct };
